# Generated by Django 3.1.7 on 2021-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('api_name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('api_key', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_json', models.TextField(default={})),
            ],
        ),
    ]
